### ISSUE TITLE
Regarding recombination rules

### ISSUE THREAD

**Issue by longkunxuluke** [Brian-hongyan/3D-MCTS#2]
Greetings. The 3D-MCTS work is very impressive. I noticed the fragment recombination rules listed in Table S1 in your paper SI has some difference with the original one in Schem 2 in [the original BRCIS paper](https://chemistry-europe.onlinelibrary.wiley.com/doi/10.1002/cmdc.200800178). For example, for fragment class 1, in the original paper matched fragments can be class  2, 3, and 10, while in your paper there is one additional class  5. I might have missed some details in your paper, I am wondering if there is any reason behind this difference? Many thanks!

**Comment by Brian-hongyan** [comment]
Dear @longkunxuluke, 

I hope this message finds you well. Thank you for your interest in our work on the 3D-MCTS and for bringing up your insightful observations regarding the fragment recombination rules in our supplementary information compared to the original BRCIS paper.

You are absolutely right in noting the differences. In our study, we included class 1 -- class 5 recombination in addition to the original rules. The reason behind this addition is based on our finding that class 5 can form amide bonds with class 1 fragments. Given that amide bonds are a prevalent substructure in drug molecules, we believed it was important to include this interaction in our model.

If you have any more questions or would like to discuss this further, please do not hesitate to contact me. I appreciate your attention to detail and interest in our research.

Best regards,
Hongyan

**Comment by longkunxuluke** [comment]
Thanks for the kind reply! A follow-up question is that it seems the fragment recombination rule in the code (line 60, `Iso_dic`) also differs with that in the SI table, so I reckon `Iso_dic` is the one finally used in your actual experiment?

**Comment by Brian-hongyan** [comment]
Yes, you are right. The `Iso_dic` is the rule we used for all experiments reported in the paper.
